Sang hun
aderbique/stressmanager pull request #14
Opened 2021-07-05 15:04 UTC by sanghoonsim

1. Deleted the heart rate part
2. Web-api

2021-07-05 17:50 UTC, aderbique requested changes
Lots of code changes in this PR. Next time, please keep PRs smaller. Otherwise, looks good.

2021-07-05 17:50 UTC, aderbique commented on application/companion/getUser.js
> +fetch('https://api.fitbit.com/1/user/-/devices.json', {
We should have a configuration file that specifies endpoints. In case this ever changes.

2021-07-05 17:50 UTC, aderbique commented on Web-app/index.html
> +    <a href="https://www.fitbit.com/oauth2/authorize?response_type=token&client_id=239YVN&redirect_uri=http%3A%2F%2F127.0.0.1%3A8887%2F&scope=activity%20heartrate%20location%20nutrition%20profile%20s
Is it possible to break this up into multiple lines to make it a little more reader friendly?

2021-07-05 17:50 UTC, aderbique commented on Web-app/js/custom.js
> +xhr.open('GET', 'https://api.fitbit.com/1/user/' + userId + '/activities/heart/date/2021-06-19/1d/1sec/time/00:00/23:59.json');
Why is this hardcoded?

2021-07-05 18:06 UTC, sanghoonsim commented on Web-app/js/custom.js
> +xhr.open('GET', 'https://api.fitbit.com/1/user/' + userId + '/activities/heart/date/2021-06-19/1d/1sec/time/00:00/23:59.json');
This part is not yet finished. We can't get heart rate data unless we request to Fitbit. I just put incomplete code.

2021-07-05 18:08 UTC, sanghoonsim commented on Web-app/index.html
> +    <a href="https://www.fitbit.com/oauth2/authorize?response_type=token&client_id=239YVN&redirect_uri=http%3A%2F%2F127.0.0.1%3A8887%2F&scope=activity%20heartrate%20location%20nutrition%20profile%20s
I will do after we get an aws accout for stress manager.

2021-07-05 18:09 UTC, sanghoonsim commented on application/companion/getUser.js
> +fetch('https://api.fitbit.com/1/user/-/devices.json', {
What do you mean end point?

2021-07-05 18:18 UTC, tparanjpe approved these changes

2021-07-05 18:18 UTC, tparanjpe commented on web-app/js/transfer_s3.js
> +AWS.config.update({
Why are all the functions in this class weirdly tabbed? Do we want to leave it like that?

2021-07-05 18:18 UTC, tparanjpe commented on web-app/js/get_info.js
> +		var clientId = "239YVN";
Assuming this is client specific, so we will also need to find a way to make this not hardcoded for the next iteration

2021-07-05 18:18 UTC, tparanjpe commented on web-app/js/get_info.js
> +			location.replace('http://127.0.0.1:8887/index.html');
This url will remain official right? no need to get some data to replace this url?

2021-07-05 18:19 UTC, tparanjpe commented on application/companion/getUser.js
> +fetch('https://api.fitbit.com/1/user/-/devices.json', {
Agreed with Austin's comment that we will need a way to make this code more generic (not hard coded for a specific user)

2021-07-05 18:24 UTC, sanghoonsim commented on web-app/js/get_info.js
> +			location.replace('http://127.0.0.1:8887/index.html');
We have to change all the specified url once we settle our account.

2021-07-05 18:24 UTC, sanghoonsim commented on web-app/js/get_info.js
> +		var clientId = "239YVN";
No, client id is for oauth app, not users. We need only one clinet id/secret.

2021-07-05 18:25 UTC, sanghoonsim commented on web-app/js/transfer_s3.js
> +AWS.config.update({
Sorry about that. I will make it look alright someday.

2021-07-05 18:30 UTC, sanghoonsim commented on application/companion/getUser.js
> +fetch('https://api.fitbit.com/1/user/-/devices.json', {
Sorry, I don't fully get your point. Since this request is made from companion, each user get their own device Id which means it is already generic??

2021-07-05 18:31 UTC, aderbique commented on application/companion/getUser.js
> +fetch('https://api.fitbit.com/1/user/-/devices.json', {
@sanghoonsim What I mean is that the HTTPS endpoint (the string) should be defined in a configuration file somewhere, not hardcoded in this getUser.js file.

2021-07-05 18:32 UTC, aderbique commented on Web-app/js/custom.js
> +xhr.open('GET', 'https://api.fitbit.com/1/user/' + userId + '/activities/heart/date/2021-06-19/1d/1sec/time/00:00/23:59.json');
If you are not using the code, please comment it out and leave a TODO comment above saying what still needs to be done.

2021-07-05 18:42 UTC, sanghoonsim commented on application/companion/getUser.js
> +fetch('https://api.fitbit.com/1/user/-/devices.json', {
@aderbique I don't think this HTTPS endpoint will change but will do as your suggestion within this week. Can you approve to merge? This part will be needed only once at the initial stage and not have critical influence on the app. Also I want you to test the Fitbit with the updated code.

2021-07-06 15:53 UTC, aderbique approved these changes

2021-07-06 23:17 UTC, merged