Update to change prompt strategy
aderbique/stressmanager pull request #17
Opened 2021-07-09 03:24 UTC by tparanjpe

Update to only prompt when heartrate has dipped below  threshold and goes up again.

2021-07-09 04:00 UTC, sanghoonsim approved these changes

2021-07-11 00:31 UTC, aderbique requested changes

2021-07-11 00:31 UTC, aderbique commented on application/app/index.js
> +var dippedBelowThreshold = true;
Let's change the variable name in case we want to expand this to other conditions in the future.  Something like 
lockout = True/False  or isAvailable or stateLock = True/False.

2021-07-13 00:20 UTC, aderbique approved these changes
Looks good!

2021-07-13 00:27 UTC, merged