Minor bug fix to button display and code clean up
aderbique/stressmanager pull request #22
Opened 2021-07-14 03:15 UTC by tparanjpe

Fixed  when the button and cycle disappear (after input is received) and cleaned up some comments

2021-07-14 03:18 UTC, sanghoonsim approved these changes

2021-07-15 00:40 UTC, aderbique requested changes

2021-07-15 00:40 UTC, aderbique commented on application/app/index.js
> +function getUserInput(Date){
What is Date? Can you please provide code comments?

2021-07-15 00:40 UTC, aderbique commented on application/app/index.js
> +  myButton.style.display = "none";
Is "none" a keyword for fitbit? Otherwise, the value should be set to null or empty string.

2021-07-16 03:45 UTC, tparanjpe commented on application/app/index.js
> +  myButton.style.display = "none";
Its a keyword for fitbit, its required.

2021-07-16 15:38 UTC, aderbique approved these changes

2021-07-18 19:44 UTC, merged