Tara UI
aderbique/stressmanager pull request #27
Opened 2021-07-30 01:40 UTC by tparanjpe

2021-07-30 04:55 UTC, sanghoonsim approved these changes

2021-07-30 16:17 UTC, aderbique requested changes

2021-07-30 16:17 UTC, aderbique commented on application/app/index.js
> +    console.log(err)
You are missing semi colons on your log statements

2021-07-30 16:17 UTC, aderbique commented on application/app/index.js
> +    console.log('No files')
You are missing semi colons on your log statements

2021-07-30 16:17 UTC, aderbique commented on application/app/index.js
> +    return dirArr
Missing semi colon

2021-07-30 16:17 UTC, aderbique commented on application/app/index.js
> +  var filename = files[0]
Missing semi colon

2021-07-31 21:20 UTC, aderbique approved these changes

2021-07-31 21:20 UTC, aderbique commented
lgtm

2021-07-31 21:45 UTC, merged